### ISSUE TITLE
Suggestion: Different Gameplay Options

### ISSUE THREAD

**Issue by mxnmnm** [TheASEStefan/RottedZombieMod#2]
Would it be possible to add a config option that treats the zombies more similarly to normal zombies (aka only spawning at night and burning during the day)? Can we also get the option to configure spawns per zombie (and maybe a height option for something like the zombie miner)? I think it would let this mod fit in more smoothly with your typical mc gameplay.

**Comment by TheASEStefan** [comment]
I'm guessing that you didn't open the config before saying this because I believe that there's a ton of config options modifying their spawn weights, go to "Spawns" and there should be an option with a lot of words, including the name of the zombies, their spawn weights and their minimum and maximum numbers of them spawning at a time. And you also have a config option for their daylight burning as well I think.

**Comment by mxnmnm** [comment]
I see the spawns are for all zombies unless there is a way to write in there that makes it per zombie. Aka having the marine zombie only spawn in ocean biomes while others might spawn in some other biome. I didn't see a daylight burning option at all.

**Comment by mxnmnm** [comment]
pretty sure I remember seeing that this mod was basically abandoned so just gonna close this
